import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased flex flex-col`}>
        <div className="p-4 flex flex-col">
          <span className="text-3xl">NootBookLM</span>
          <div className="max-w-5xl w-full mx-auto">{children}</div>
        </div>
        <Toaster />
        <Image
          src={"/assets/wave.svg"}
          width={100}
          height={100}
          alt=""
          className="fixed bottom-0 left-0 right-0 w-screen z-[-1]"
        />
      </body>
    </html>
  );
}
